name: BitcoinNova Electonic Wallet - Build
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.target }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-msvc,
            x86_64-apple-darwin,
            x86_64-unknown-linux-gnu,
          ]
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup MSBuild.exe
        if: matrix.os == 'windows-latest'
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.os }}-deps

      - name: Dependencies
        run: yarn

      - name: Build for Windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          yarn dist-win
      - name: Build for MacOS
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          chmod +x ./bin/osx/Bitcoinnova-service
          yarn dist-mac
      - name: Build for Linux
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          chmod +x ./bin/lin/Bitcoinnova-service
          yarn dist-lin
      - name: Prepare to Deploy
        id: before_deploy
        shell: bash
        run: |
          rm -rf ./dist/*.blockmap
          rm -rf ./dist/*.zip
          rm -rf ./dist/*-unpacked
          rm -rf ./dist/mac
          export NAME=$(ls dist/ElectronWallet-*)
          echo ::set-output name=file_name::${NAME:5}
