name: Build WrkzWalletShell
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.target }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-msvc,
            x86_64-apple-darwin,
            x86_64-unknown-linux-gnu,
          ]
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup MSBuild.exe
        if: matrix.os == 'windows-latest'
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.os }}-deps

      - name: Dependencies
        run: yarn

      - name: Build for Windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          yarn dist-win
      - name: Build for MacOS
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          chmod +x ./bin/osx/Bitcoinnova-service
          yarn dist-mac
      - name: Build for Linux
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          chmod +x ./bin/lin/Bitcoinnova-service
          yarn dist-lin
      - name: Prepare to Deploy
        id: before_deploy
        shell: bash
        run: |
          rm -rf ./dist/*.blockmap
          rm -rf ./dist/*.zip
          rm -rf ./dist/*-unpacked
          rm -rf ./dist/mac
          export NAME=$(ls dist/Electron Wallet-*)
          echo ::set-output name=file_name::${NAME:5}
          
          # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.before_deploy.outputs.artifact_name }}
          path: ./dist/
                   
      # Upload to GH Release

      - name: Upload to GH Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/${{ steps.before_deploy.outputs.artifact_name }}
          asset_name: ${{ steps.before_deploy.outputs.artifact_name }}
          asset_content_type: application/zip
